ALTER TABLE EMPLOYEES
ADD COLUMN state VARCHAR(15) AFTER name;

UPDATE EMPLOYEES
SET state = Texas
WHERE PHONE_NUMBER LIKE '7%';

UPDATE EMPLOYEES
SET state = Phoenix
WHERE PHONE_NUMBER LIKE '3%';

UPDATE EMPLOYEES
SET state = New York
WHERE PHONE_NUMBER LIKE '8%';